"""create user and blog table migrations

Revision ID: 67759fdd5c03
Revises: ec16da6e3383
Create Date: 2026-01-30 17:25:16.859523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67759fdd5c03'
down_revision = 'ec16da6e3383'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
